### ISSUE TITLE
No such file to load -- resque_web/application_controller

### ISSUE THREAD

**Issue by jcoyne** [resque/resque-web#101]
When I deploy an application that uses resque-web 0.0.7 in production mode I get the following error.
```
 Message from application: No such file to load -- resque_web/application_controller (LoadError)
  /opt/goldenseal/shared/bundle/ruby/2.2.0/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:274:in `require'
  /opt/goldenseal/shared/bundle/ruby/2.2.0/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:274:in `block in require'
  /opt/goldenseal/shared/bundle/ruby/2.2.0/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:240:in `load_dependency'
  /opt/goldenseal/shared/bundle/ruby/2.2.0/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:274:in `require'
  /opt/goldenseal/shared/bundle/ruby/2.2.0/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:360:in `require_or_load'
  /opt/goldenseal/shared/bundle/ruby/2.2.0/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:317:in `depend_on'
  /opt/goldenseal/shared/bundle/ruby/2.2.0/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:233:in `require_dependency'
  /opt/goldenseal/shared/bundle/ruby/2.2.0/gems/railties-4.2.5/lib/rails/engine.rb:472:in `block (2 levels) in eager_load!'
  /opt/goldenseal/shared/bundle/ruby/2.2.0/gems/railties-4.2.5/lib/rails/engine.rb:471:in `each'
  /opt/goldenseal/shared/bundle/ruby/2.2.0/gems/railties-4.2.5/lib/rails/engine.rb:471:in `block in eager_load!'
  /opt/goldenseal/shared/bundle/ruby/2.2.0/gems/railties-4.2.5/lib/rails/engine.rb:469:in `each'
  /opt/goldenseal/shared/bundle/ruby/2.2.0/gems/railties-4.2.5/lib/rails/engine.rb:469:in `eager_load!'
  /opt/goldenseal/shared/bundle/ruby/2.2.0/gems/railties-4.2.5/lib/rails/engine.rb:346:in `eager_load!'
  /opt/goldenseal/shared/bundle/ruby/2.2.0/gems/railties-4.2.5/lib/rails/application/finisher.rb:56:in `each'
  /opt/goldenseal/shared/bundle/ruby/2.2.0/gems/railties-4.2.5/lib/rails/application/finisher.rb:56:in `block in <module:Finisher>'
  /opt/goldenseal/shared/bundle/ruby/2.2.0/gems/railties-4.2.5/lib/rails/initializable.rb:30:in `instance_exec'
  /opt/goldenseal/shared/bundle/ruby/2.2.0/gems/railties-4.2.5/lib/rails/initializable.rb:30:in `run'
  /opt/goldenseal/shared/bundle/ruby/2.2.0/gems/railties-4.2.5/lib/rails/initializable.rb:55:in `block in run_initializers'
  /usr/local/lib/ruby/2.2.0/tsort.rb:226:in `block in tsort_each'
  /usr/local/lib/ruby/2.2.0/tsort.rb:348:in `block (2 levels) in each_strongly_connected_component'
  /usr/local/lib/ruby/2.2.0/tsort.rb:429:in `each_strongly_connected_component_from'
  /usr/local/lib/ruby/2.2.0/tsort.rb:347:in `block in each_strongly_connected_component'
  /usr/local/lib/ruby/2.2.0/tsort.rb:345:in `each'
  /usr/local/lib/ruby/2.2.0/tsort.rb:345:in `call'
  /usr/local/lib/ruby/2.2.0/tsort.rb:345:in `each_strongly_connected_component'
  /usr/local/lib/ruby/2.2.0/tsort.rb:224:in `tsort_each'
  /usr/local/lib/ruby/2.2.0/tsort.rb:203:in `tsort_each'
  /opt/goldenseal/shared/bundle/ruby/2.2.0/gems/railties-4.2.5/lib/rails/initializable.rb:54:in `run_initializers'
  /opt/goldenseal/shared/bundle/ruby/2.2.0/gems/railties-4.2.5/lib/rails/application.rb:352:in `initialize!'
  /opt/goldenseal/releases/20160104213118/config/environment.rb:5:in `<top (required)>'
  config.ru:3:in `require'
```

I can achieve the same effect by generating a new application, adding resque-web to the gemfile, running bundle install, then rails console and entering:

```ruby 
require 'resque_web'
=> true
irb(main):003:0> ResqueWeb::Engine.eager_load!
LoadError: No such file to load -- resque_web/application_controller
...
```

**Comment by jcoyne** [comment]
When I turn on logging it shows the following:
```
ActiveSupport::Dependencies.logger = Rails.logger
ActiveSupport::Dependencies.log_activity = true
require 'resque_web'
ResqueWeb::Engine.eager_load!

Dependencies: called require_or_load("resque_web/application_controller", nil)
Dependencies: loading resque_web/application_controller
loading resque_web/application_controller.rb
Dependencies: called load_file("resque_web/application_controller.rb", [])
Dependencies: called new_constants_in()
Dependencies: New constants:
Dependencies: Error during loading, removing partially loaded constants
LoadError: No such file to load -- resque_web/application_controller
```

**Comment by jcoyne** [comment]
It doesn't appear to be getting loaded as an engine:
```
::Rails::Engine.subclasses
=> [Coffee::Rails::Engine, Jquery::Rails::Engine, Turbolinks::Engine]
```

**Comment by jcoyne** [comment]
Apparently, I can't follow instructions. You have to have the `require: 'resque_web'` in the Gemfile.

**Comment by mcfiredrill** [comment]
@jcoyne Glad you figured it out. 

If there was a way to make it work without the `require` I'd probably accept a PR for that...
